name: todoo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta
 
dependencies:
  flutter:
    sdk: flutter
  intl:
  sqflite:
  get:
  get_storage :
  date_picker_timeline:
  flutter_staggered_animations:
  flutter_local_notifications:
  flutter_screenutil:
 
   # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^6.0.0

 
flutter:
 
  uses-material-design: true
 

  assets:
    - assets/img1.png
    - assets/img2.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"